// components/Control/control-section.vue
<script lang="ts" setup>
import { useSelectedMusicStore } from "~/stores/selectedMusicStore";
import { useVolumeStore } from "~/stores/volumeStore";
import { normalizeTimeFormat } from "~/utils/utils";
let { shuffle, playNext, playPrevious } = useSelectedMusicStore();
let selectedMusic = useSelectedMusicStore();
let currentTrack = selectedMusic.currentTrack;
const paused = ref(true);

function toggleMusicState() {
    audio.value.paused ? audio.value.play() : audio.value.pause();
    paused.value = audio.value.paused;
}
const audio = ref<HTMLAudioElement>();
let currentTime = ref(0);

selectedMusic.$subscribe((mutation, state) => {
    if (
        selectedMusic.currentTrack &&
        // @ts-ignore
        mutation.events.oldValue?.src !== mutation.events.newValue?.src
    ) {
        audio.value.src = selectedMusic.currentTrack.src as string;
        audio.value.play();
    }
});

const audioLoop = ref(false);
function handleLoop() {
    if (!audio.value) return;
    audio.value.loop = !audio.value.loop;
    audioLoop.value = audio.value.loop;
}

function handleLadderChange(e: Event) {
    audio.value.currentTime = (e.target as HTMLInputElement)
        .value as unknown as number;
}

setInterval(() => {
    currentTime.value = Math.round(audio.value?.currentTime || 0);
}, 1000);

onMounted(() => {
    audio.value.addEventListener("ended", () => {
        playNext();
    });
    audio.value.addEventListener("play", () => {
        paused.value = false;
    });
});

useVolumeStore().$subscribe(() => {
    audio.value.volume = useVolumeStore().volume / 100;
});
</script>

<template>
    <div class="control-section">
        <audio :src="currentTrack?.src as string" ref="audio" hidden autoplay />
        <div class="control-buttons">
            <button
                class="ripple button repeat"
                :class="{ active: audioLoop }"
                @click="handleLoop">
                <v-icon name="ri-repeat-2-fill" scale="1.5"></v-icon>
            </button>
            <button class="ripple button prev" @click="playPrevious">
                <v-icon name="md-skipprevious-round" scale="1.5"></v-icon>
            </button>
            <button class="ripple button play" @click="toggleMusicState">
                <v-icon
                    :name="paused ? 'bi-play-fill' : 'io-pause'"
                    scale="3"></v-icon>
            </button>
            <button class="ripple button next" @click="playNext">
                <v-icon name="md-skipnext-round" scale="1.5"></v-icon>
            </button>

            <button class="ripple button shuffle" @click="shuffle">
                <v-icon name="bi-shuffle" scale="1.5"></v-icon>
            </button>
        </div>
        <div class="ladder">
            <span>{{ normalizeTimeFormat(currentTime) }}</span>
            <input
                type="range"
                class="progress"
                :value="currentTime"
                min="0"
                :max="Math.round(selectedMusic.currentTrack?.duration || 10)"
                @input="handleLadderChange" />
            <span>{{
                normalizeTimeFormat(selectedMusic.currentTrack?.duration)
            }}</span>
        </div>
    </div>
</template>

<style lang="scss" scoped>
@mixin flex-center() {
    display: flex;
    justify-content: center;
    align-items: center;
}

.control-section {
    @include flex-center();
    flex-direction: column;
    width: 100%;

    .control-buttons {
        @include flex-center();
        flex-direction: row;

        .button {
            outline: var(--theme);
            border-radius: 50%;
            padding: 5px;
            margin: 2px 5px;

            &.active {
                color: var(--theme) !important;
            }
        }
    }

    .ladder {
        @include flex-center();
        flex-direction: row;
        width: min(100%, 550px);

        span {
            margin: 0 10px;
        }

        .progress {
            position: relative;
            appearance: none;
            flex-grow: 1;
            height: 8px;
            border-radius: 50px;
            display: block;
            background: var(--color);
            outline: none;
            overflow: hidden;
            transition: 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);

            &::-webkit-slider-thumb {
                appearance: none;
                height: 15px;
                width: 15px;
                background: var(--theme);
                border-radius: 50%;
                cursor: ew-resize;
                box-shadow: -1007.5px 0 0 1000px var(--theme);
            }

            &:hover {
                height: 15px;
            }
        }
    }
}

@media (max-width: 367px) {
    .control-section {
        .control-buttons {
            .button {
                padding: 1px;
                margin: 0;
            }
        }
    }
}
</style>

// components/Control/ControlSection.tsx
import { IoRepeat, IoShuffle } from "react-icons/io5";
import { MdSkipNext, MdSkipPrevious } from "react-icons/md";
import styles from "@styles/ControlPanel.module.scss";
import { normalizeTimeFormat } from "@utils/utils";
import { FaPlay } from "react-icons/fa";
import { useEffect, useRef, useState } from "react";
import { useSelectMusic } from "@contexts/SelectMusic";
import { useVolumeHandle } from "@contexts/VolumeHandle";
import { GiPauseButton } from "react-icons/gi";
import RangeSlider from "./RangeSlider";

export default function ControlSection() {
    const {
        value: selectedMusic,
        playNext,
        playPrevious,
        shuffle,
    } = useSelectMusic();
    const volume = useVolumeHandle().value;
    const audioRef = useRef<HTMLAudioElement>(null);
    const [loop, setLoop] = useState(false);
    const [paused, setPaused] = useState(true);
    const [currentTime, setCurrentTime] = useState(0);

    useEffect(() => {
        let audio = audioRef.current;
        if (!audio) return;

        audio.volume = volume / 100;
    }, [volume]);

    useEffect(() => {
        setInterval(() => {
            setCurrentTime(Math.floor(audioRef.current?.currentTime || 0));
        }, 1000);
    }, []);

    return (
        <div className={`${styles["control-section"]}`}>
            <audio
                src={(selectedMusic?.src as string) || ""}
                hidden
                ref={audioRef}
            />
            <div className={styles["control-buttons"]}>
                <button
                    className={`ripple repeat ${styles.button} ${
                        loop ? styles.active : ""
                    }`}
                    onClick={() => {
                        audioRef.current.loop = !audioRef.current?.loop;
                        setLoop(audioRef.current?.loop);
                    }}>
                    <IoRepeat size="2rem" />
                </button>
                <button
                    className={`ripple prev ${styles.button}`}
                    onClick={playPrevious}>
                    <MdSkipPrevious size="2rem" />
                </button>
                <button
                    className={`ripple play-pause ${styles.button}`}
                    style={{ padding: "10px" }}
                    onClick={async () => {
                        audioRef.current.paused
                            ? await audioRef.current.play()
                            : audioRef.current.pause();
                        setPaused(audioRef.current.paused);
                    }}>
                    {paused ? (
                        <FaPlay size="2.5rem" />
                    ) : (
                        <GiPauseButton size="2.5rem" />
                    )}
                </button>
                <button
                    className={`ripple next ${styles.button}`}
                    onClick={playNext}>
                    <MdSkipNext size="2rem" />
                </button>
                <button
                    className={`ripple shuffle ${styles.button}`}
                    onClick={shuffle}>
                    <IoShuffle size="2rem" />
                </button>
            </div>
            <div className={styles.ladder}>
                <span>{normalizeTimeFormat(currentTime)}</span>
                {/* <input
                    type="range"
                    className={styles.progress}
                    value={currentTime}
                    min="0"
                    max={selectedMusic?.duration || 0}
                    onChange={e => {
                        audioRef.current.currentTime = Number(e.target.value);
                    }}
                /> */}
                <RangeSlider
                    min={0}
                    max={selectedMusic?.duration || 0}
                    value={currentTime}
                    onChange={(e, n, a) => {
                        audioRef.current.currentTime = Number(n);
                    }}
                />
                <span>{normalizeTimeFormat(selectedMusic?.duration || 0)}</span>
            </div>
        </div>
    );
}
