// pages/lyrics.vue
<script lang="ts" setup>
import { useMusicStore } from "~/stores/musicStore";
const musicStore = useMusicStore();
const route = useRoute();
const { song, artist, id, lyrics } = route.query;
const res = ref();
res.value = lyrics;
if (
    // if they exist
    song &&
    artist &&
    id &&
    lyrics === ""
) {
    $fetch(`/api/lyrics?song=${song}&artist=${artist}`)
        .then(r => {
            // @ts-ignore
            res.value = r.lyrics;

            if (id !== "") {
                let index = musicStore.tracks.findIndex(t => t.id === id);
                if (index !== -1) {
                    // @ts-ignore
                    musicStore.tracks[index].lyrics = r.lyrics;
                }
            }
        })
        .catch(() => {});
}
definePageMeta({
    pageTransition: {
        mode: "in-out",
        name: "page",
    },
});
</script>
<template>
    <main-body title="Lyrics">
        <pre
            >{{ res }}
        
        
        </pre>
    </main-body>
</template>

<style lang="scss" scoped>
pre {
    text-align: center;
    font-size: 1.3rem;
    font-family: inherit;
    overflow-y: auto;
    height: calc(100% - 50px);
}
</style>

// pages/lyrics.tsx
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import MainBody from "@components/MainBody";
import styles from "@styles/Home.module.scss";
import { useMusicStore } from "@contexts/MusicStore";
import { useSelectMusic } from "@contexts/SelectMusic";

export default function Lyrics() {
    const route = useRouter();
    const musicStore = useMusicStore();
    const selectedMusic = useSelectMusic();
    const [res, setRes] = useState(route.query?.lyrics || "");
    useEffect(() => {
        if (Object.keys(route.query).length === 0) return;
        let { song, artist, id, lyrics } = route.query;
        if (
            // if they do not exist, return
            !song &&
            !artist &&
            !id &&
            lyrics !== ""
        )
            return;
        fetch(`/api/lyrics?song=${song}&artist=${artist}`)
            .then(r => r.json())
            .then((r: any) => {
                setRes(r.lyrics);

                if (id === "") return;
                let index = musicStore.value.findIndex(t => t.id === id);
                if (index !== -1) {
                    musicStore.setValue(prev => {
                        let temp = [...prev];
                        temp[index].lyrics = r.lyrics;
                        return temp;
                    });
                }
                selectedMusic.setValue(prev => {
                    let temp = { ...prev };
                    temp.lyrics = r.lyrics;
                    return temp;
                });
            })
            .catch(() => {});

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [route]);

    return (
        <>
            <Head>
                <title>
                    Lyrics - {route.query?.song} by {route.query?.artist}
                </title>
            </Head>
            <MainBody title="Lyrics">
                <div className={styles.lyrics}>
                    <h2>
                        {route.query?.song} - {route.query?.artist}
                    </h2>
                    <pre>
                        {res}
                        <br />
                        <br />
                        <br />
                    </pre>
                </div>
            </MainBody>
        </>
    );
}
